CREATE TABLE "DB_SEMILLERO"."PERSONA" 
(	
  "PERSONA_ID" NUMBER(3,0) NOT NULL ENABLE,
  "PERSONA_NOMBRE" VARCHAR2(150 BYTE) NOT NULL  ENABLE, 
  "PERSONA_TIPODOCUMENTO" VARCHAR2(50 BYTE) NOT NULL  ENABLE, 
  "PERSONA_DOCUMENTO" VARCHAR2(20 BYTE) NOT NULL ENABLE,
  "PERSONA_FNACIMIENTO" date,
  CONSTRAINT "PK_PERSONA" PRIMARY KEY ("PERSONA_ID"),
  CONSTRAINT "PERSONA_TIPODOCUMENTO_CHK" CHECK (PERSONA_TIPODOCUMENTO IN ('CEDULA_CIUDADANIA', 'CEDULA_EXTRANJERIA', 'PASAPORTE', 'OTRO'))
);
create sequence "SEQ_PERSONA" minvalue 1 start with 1 increment by 1;
CREATE UNIQUE INDEX UNQ_PERSONA_DOCUMENTO ON PERSONA(PERSONA_TIPODOCUMENTO,PERSONA_DOCUMENTO);
--DROP SEQUENCE "SEQ_PERSONA";
--DROP TABLE PERSONA;
--{"nombre":"Ebert Zerpa","tipoDocumento":"CEDULA_EXTRANJERIA","documento":"17576172","fnacimiento":"1987-01-01"}
select * from persona;
