CREATE TABLE "DB_SEMILLERO"."FACTURA" 
(	
  "FACTURA_ID" NUMBER(3,0) NOT NULL ENABLE,
  "FACTURA_PERSONA_ID" NUMBER(3,0) NOT NULL ENABLE, 
  "FACTURA_COMIC_ID" NUMBER(3,0) NOT NULL ENABLE,
  "FACTURA_FECHA" TIMESTAMP
);
CREATE SEQUENCE "SEQ_FACTURA" minvalue 1 start with 1 increment by 1;
ALTER TABLE FACTURA ADD CONSTRAINT "PK_FACTURA" PRIMARY KEY ("FACTURA_ID");
ALTER TABLE FACTURA ADD CONSTRAINT "FK_FACTURA_PERSONA_ID" FOREIGN KEY (FACTURA_PERSONA_ID) REFERENCES PERSONA(PERSONA_ID);
ALTER TABLE FACTURA ADD CONSTRAINT "FK_FACTURA_COMIC_ID" FOREIGN KEY (FACTURA_COMIC_ID) REFERENCES COMIC(SCID);


select * from FACTURA;
